### ISSUE TITLE
[1.19.2] 2.3.0 Server Crash

### ISSUE THREAD

**Issue by suerion** [OverlordsIII/NPCVarietyPort#23]
Hey, Our Server Crash on 2.3.0 version, no Problems on 2.2.2

```
[19:08:26] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_1642::method_5874(Lnet/minecraft/class_3218;Lnet/minecraft/class_1309;)Z has incompatible changes at opcode 95 in callback npcvariety.mixins.json:ZombieEntityMixin from mod npcvariety->@Inject::setZombieVillagerSkinIndex(Lnet/minecraft/class_3218;Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ZLnet/minecraft/class_1646;Lnet/minecraft/class_1641;)V.
 Expected: [Z, Lnet/minecraft/class_1646;, Lnet/minecraft/class_1641;]
    Found: [Lnet/minecraft/class_1646;, Lnet/minecraft/class_1641;]
Available: [Lnet/minecraft/class_1646;, Lnet/minecraft/class_1641;]
[19:08:26] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1642 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1642 failed
	at net.minecraft.class_1299.<clinit>(class_1299.java:187) ~[server-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:84) ~[server-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[server-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:24) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1642 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:187) ~[server-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:84) ~[server-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[server-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:24) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:187) ~[server-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:84) ~[server-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[server-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:24) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1642::method_5874(Lnet/minecraft/class_3218;Lnet/minecraft/class_1309;)Z has incompatible changes at opcode 95 in callback npcvariety.mixins.json:ZombieEntityMixin from mod npcvariety->@Inject::setZombieVillagerSkinIndex(Lnet/minecraft/class_3218;Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ZLnet/minecraft/class_1646;Lnet/minecraft/class_1641;)V.
 Expected: [Z, Lnet/minecraft/class_1646;, Lnet/minecraft/class_1641;]
    Found: [Lnet/minecraft/class_1646;, Lnet/minecraft/class_1641;]
Available: [Lnet/minecraft/class_1646;, Lnet/minecraft/class_1641;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:187) ~[server-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:84) ~[server-intermediary.jar:?]
	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[server-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:24) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 4 more
```

**Comment by suerion** [comment]
I think, on Modrinth there is an error on Supported versions -> On curseforge, there is 2.2.2 only for 1.19.2, on modrinth there is 1.19-1.19.4 Support. Could be there is the error

![grafik](https://github.com/OverlordsIII/NPCVarietyPort/assets/55131959/ce77f317-ad37-4b89-bf43-db516bbfeb8b)

**Comment by suerion** [comment]
![grafik](https://github.com/OverlordsIII/NPCVarietyPort/assets/55131959/9f578ea5-d490-4e33-9c96-30dd3e5bc399)
